name: Release
on: push

permissions:
  contents: write

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./main
          quiet: true
          soft_fail: true
          framework: terraform
          output_format: github_failed_only
          download_external_modules: true
          log_level: WARNING
          container_user: 1000

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: ./main
          output-file: README.md
          output-method: inject
          git-push: "true"
